### ISSUE TITLE
关于yolov5版本

### ISSUE THREAD

**Issue by johnzhy** [zhang-jiaqi-1207/plate-detect-pt2rk#1]
您好，yolov5的pt文件转rknn格式，对yolov5版本有要求吗，你这个使用的哪个版本的yolov5，不同yolov5版本对结果有影响吗。
我使用的是rv1126，需要用到rknn-toolkit1，您的代码可以使用吗。

**Comment by zhang-jiaqi-1207** [comment]
## 关于yolov5版本

- 我这个项目的车牌检测部分使用的是[中文车牌检测](https://github.com/we0091234/Chinese_license_plate_detection_recognition)这个开源仓库下的代码。原作者并没有给出使用的yolov5版本（也可能是我没注意到）。您可以在该仓库下`/mode/yolo.py`文件中查看作者使用的模型与你要部署模型的差异。

- 此外，如果您使用的是标准的yolov5模型，没有进行结构上修改的话，可以参考[RKNN Model ZOO](https://github.com/airockchip/rknn_model_zoo)这个开源仓库。其中的`models/CV/object_detection/yolov/`路径下有较为完整的教程，以及结果对比。

## 代码是否可以使用

在您认为有所帮助的前提下，可以根据您的需要进行使用，但是有几点说明：

- `rknn_toolkit1`与`rknn_toolkit2`的API接口可能会有不同，可能需要您根据具体的文档说明进行修改。

- 目前的代码还没有完全完成。目前只是在PC端以仿真器的模式进行运行，而且如你所见`do_quantization`参数为`False`，说明并未进行量化，还是`fp16`的数据格式。距离上板部署还有一段距离，目前我也在慢慢推进。
